"""empty message

Revision ID: 226bd4964026
Revises: 439ca74f90c5
Create Date: 2019-04-13 13:35:31.373755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '226bd4964026'
down_revision = '439ca74f90c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file_content', 'filename',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=400),
               existing_nullable=False)
    op.alter_column('file_content', 'path_file',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('futcontract', 'fut_price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=8),
               existing_nullable=False)
    op.alter_column('futcontract', 'fut_sett',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=8),
               existing_nullable=True)
    op.alter_column('greeksopt', 'delta_call',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=False)
    op.alter_column('greeksopt', 'delta_put',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=False)
    op.alter_column('greeksopt', 'gamma_call',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=False)
    op.alter_column('greeksopt', 'gamma_put',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=False)
    op.alter_column('greeksopt', 'rho_call',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=False)
    op.alter_column('greeksopt', 'rho_put',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=False)
    op.alter_column('greeksopt', 'theta_call',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=False)
    op.alter_column('greeksopt', 'theta_put',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=False)
    op.alter_column('greeksopt', 'vega_call',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=False)
    op.alter_column('greeksopt', 'vega_put',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=False)
    op.alter_column('options', 'opt_strike',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=8),
               existing_nullable=False)
    op.alter_column('options', 'theo_price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=8),
               existing_nullable=False)
    op.alter_column('options', 'vol_opt',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=6),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('options', 'vol_opt',
               existing_type=sa.Float(precision=6),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('options', 'theo_price',
               existing_type=sa.Float(precision=8),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('options', 'opt_strike',
               existing_type=sa.Float(precision=8),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('greeksopt', 'vega_put',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('greeksopt', 'vega_call',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('greeksopt', 'theta_put',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('greeksopt', 'theta_call',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('greeksopt', 'rho_put',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('greeksopt', 'rho_call',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('greeksopt', 'gamma_put',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('greeksopt', 'gamma_call',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('greeksopt', 'delta_put',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('greeksopt', 'delta_call',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('futcontract', 'fut_sett',
               existing_type=sa.Float(precision=8),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('futcontract', 'fut_price',
               existing_type=sa.Float(precision=8),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('file_content', 'path_file',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False)
    op.alter_column('file_content', 'filename',
               existing_type=sa.String(length=400),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False)
    # ### end Alembic commands ###
