"""empty message

Revision ID: 2c0b76d6c5cf
Revises: 
Create Date: 2019-04-26 09:18:18.948457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c0b76d6c5cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bizname', sa.String(length=400), nullable=False),
    sa.Column('folder_path', sa.String(length=400), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instrument',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_inst', sa.String(length=20), nullable=False),
    sa.Column('descr_inst', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('month_c',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month_name', sa.String(length=20), nullable=False),
    sa.Column('month_letter', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('futures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fut_name', sa.String(length=20), nullable=False),
    sa.Column('fut_sym', sa.String(length=8), nullable=False),
    sa.Column('inst_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['inst_id'], ['instrument.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_name', sa.String(length=20), nullable=False),
    sa.Column('stock_sym', sa.String(length=20), nullable=False),
    sa.Column('inst_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['inst_id'], ['instrument.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('image_file', sa.String(length=20), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('last_message_read_time', sa.DateTime(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_company', sa.String(length=30), nullable=False),
    sa.Column('sym_company', sa.String(length=8), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('filecontent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=400), nullable=False),
    sa.Column('path_file', sa.String(length=500), nullable=False),
    sa.Column('date_upload', sa.DateTime(), nullable=False),
    sa.Column('down_date', sa.DateTime(), nullable=True),
    sa.Column('extension', sa.String(length=5), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path_file')
    )
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    op.create_table('futcontract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fut_year', sa.String(length=10), nullable=False),
    sa.Column('futctr_sym', sa.String(length=8), nullable=False),
    sa.Column('fut_exp', sa.DateTime(), nullable=False),
    sa.Column('fut_price', sa.Float(precision=8), nullable=False),
    sa.Column('date_price', sa.DateTime(), nullable=False),
    sa.Column('fut_sett', sa.Float(precision=8), nullable=True),
    sa.Column('fut_id', sa.Integer(), nullable=False),
    sa.Column('ctrf_month', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ctrf_month'], ['month_c.id'], ),
    sa.ForeignKeyConstraint(['fut_id'], ['futures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_timestamp'), 'message', ['timestamp'], unique=False)
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_name'), 'notification', ['name'], unique=False)
    op.create_index(op.f('ix_notification_timestamp'), 'notification', ['timestamp'], unique=False)
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('under_n', sa.String(length=8), nullable=False),
    sa.Column('theo_price', sa.Float(precision=8), nullable=False),
    sa.Column('date_calc', sa.DateTime(), nullable=True),
    sa.Column('opt_strike', sa.Float(precision=8), nullable=False),
    sa.Column('opt_sym', sa.String(length=8), nullable=False),
    sa.Column('exp_date', sa.DateTime(), nullable=True),
    sa.Column('date_val', sa.DateTime(), nullable=True),
    sa.Column('vol_opt', sa.Float(precision=6), nullable=False),
    sa.Column('futctr_id', sa.Integer(), nullable=False),
    sa.Column('contract', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contract'], ['month_c.id'], ),
    sa.ForeignKeyConstraint(['futctr_id'], ['futcontract.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('greeksopt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delta_put', sa.Float(precision=10), nullable=False),
    sa.Column('delta_call', sa.Float(precision=10), nullable=False),
    sa.Column('gamma_put', sa.Float(precision=10), nullable=False),
    sa.Column('gamma_call', sa.Float(precision=10), nullable=False),
    sa.Column('theta_put', sa.Float(precision=10), nullable=False),
    sa.Column('theta_call', sa.Float(precision=10), nullable=False),
    sa.Column('vega_put', sa.Float(precision=10), nullable=False),
    sa.Column('vega_call', sa.Float(precision=10), nullable=False),
    sa.Column('rho_put', sa.Float(precision=10), nullable=False),
    sa.Column('rho_call', sa.Float(precision=10), nullable=False),
    sa.Column('opt_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['opt_id'], ['options.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('greeksopt')
    op.drop_table('post_like')
    op.drop_table('options')
    op.drop_table('post')
    op.drop_index(op.f('ix_notification_timestamp'), table_name='notification')
    op.drop_index(op.f('ix_notification_name'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_message_timestamp'), table_name='message')
    op.drop_table('message')
    op.drop_table('futcontract')
    op.drop_table('followers')
    op.drop_table('filecontent')
    op.drop_table('companies')
    op.drop_table('user')
    op.drop_table('stock')
    op.drop_table('futures')
    op.drop_table('month_c')
    op.drop_table('instrument')
    op.drop_table('business')
    # ### end Alembic commands ###
