"""adding filecontent

Revision ID: 439ca74f90c5
Revises: 677dd3b26c8a
Create Date: 2019-04-13 12:50:25.704643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '439ca74f90c5'
down_revision = '677dd3b26c8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=40), nullable=False),
    sa.Column('path_file', sa.String(length=40), nullable=False),
    sa.Column('date_upload', sa.DateTime(), nullable=False),
    sa.Column('down_date', sa.DateTime(), nullable=True),
    sa.Column('extension', sa.String(length=5), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path_file')
    )
    op.drop_table('fold')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fold',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name_folder', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fold_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='fold_pkey'),
    sa.UniqueConstraint('name_folder', name='fold_name_folder_key')
    )
    op.drop_table('file_content')
    # ### end Alembic commands ###
