"""empty message

Revision ID: 677dd3b26c8a
Revises: d11193222b36
Create Date: 2019-04-13 12:35:48.191527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '677dd3b26c8a'
down_revision = 'd11193222b36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fold',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_folder', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_folder')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fold')
    # ### end Alembic commands ###
