"""change date of message

Revision ID: 67a1ee913526
Revises: 539cdccd3ebf
Create Date: 2019-03-22 22:11:05.567120

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '67a1ee913526'
down_revision = '539cdccd3ebf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('date_send', sa.Float(), nullable=True))
    op.create_index(op.f('ix_notification_date_send'), 'notification', ['date_send'], unique=False)
    op.drop_index('ix_notification_timestamp', table_name='notification')
    op.drop_column('notification', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('timestamp', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_index('ix_notification_timestamp', 'notification', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_notification_date_send'), table_name='notification')
    op.drop_column('notification', 'date_send')
    # ### end Alembic commands ###
