"""empty message

Revision ID: 9e0f9fa5a3ee
Revises: 226bd4964026
Create Date: 2019-04-13 14:16:00.984822

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9e0f9fa5a3ee'
down_revision = '226bd4964026'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filecontent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=400), nullable=False),
    sa.Column('path_file', sa.String(length=500), nullable=False),
    sa.Column('date_upload', sa.DateTime(), nullable=False),
    sa.Column('down_date', sa.DateTime(), nullable=True),
    sa.Column('extension', sa.String(length=5), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path_file')
    )
    op.drop_table('file_content')
    op.alter_column('futcontract', 'fut_price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=8),
               existing_nullable=False)
    op.alter_column('futcontract', 'fut_sett',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=8),
               existing_nullable=True)
    op.alter_column('greeksopt', 'delta_call',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=False)
    op.alter_column('greeksopt', 'delta_put',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=False)
    op.alter_column('greeksopt', 'gamma_call',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=False)
    op.alter_column('greeksopt', 'gamma_put',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=False)
    op.alter_column('greeksopt', 'rho_call',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=False)
    op.alter_column('greeksopt', 'rho_put',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=False)
    op.alter_column('greeksopt', 'theta_call',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=False)
    op.alter_column('greeksopt', 'theta_put',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=False)
    op.alter_column('greeksopt', 'vega_call',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=False)
    op.alter_column('greeksopt', 'vega_put',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=False)
    op.alter_column('options', 'opt_strike',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=8),
               existing_nullable=False)
    op.alter_column('options', 'theo_price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=8),
               existing_nullable=False)
    op.alter_column('options', 'vol_opt',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=6),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('options', 'vol_opt',
               existing_type=sa.Float(precision=6),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('options', 'theo_price',
               existing_type=sa.Float(precision=8),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('options', 'opt_strike',
               existing_type=sa.Float(precision=8),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('greeksopt', 'vega_put',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('greeksopt', 'vega_call',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('greeksopt', 'theta_put',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('greeksopt', 'theta_call',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('greeksopt', 'rho_put',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('greeksopt', 'rho_call',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('greeksopt', 'gamma_put',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('greeksopt', 'gamma_call',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('greeksopt', 'delta_put',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('greeksopt', 'delta_call',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('futcontract', 'fut_sett',
               existing_type=sa.Float(precision=8),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('futcontract', 'fut_price',
               existing_type=sa.Float(precision=8),
               type_=sa.REAL(),
               existing_nullable=False)
    op.create_table('file_content',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=400), autoincrement=False, nullable=False),
    sa.Column('path_file', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('date_upload', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('down_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('extension', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='file_content_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='file_content_pkey'),
    sa.UniqueConstraint('path_file', name='file_content_path_file_key')
    )
    op.drop_table('filecontent')
    # ### end Alembic commands ###
