"""folder

Revision ID: d11193222b36
Revises: 8331384ae5d5
Create Date: 2019-03-30 13:16:41.158852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd11193222b36'
down_revision = '8331384ae5d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fold', sa.Column('name_folder', sa.String(length=40), nullable=False))
    op.create_unique_constraint(None, 'fold', ['name_folder'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fold', type_='unique')
    op.drop_column('fold', 'name_folder')
    # ### end Alembic commands ###
